// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIPZlgZ4IFW4bP8IZZfKNXToWzNmtykqw',
    appId: '1:719901521562:web:19ecd2bf9c775c64295123',
    messagingSenderId: '719901521562',
    projectId: 'musicknew',
    authDomain: 'musicknew.firebaseapp.com',
    storageBucket: 'musicknew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzAgzO4JfFlmObDrz6hWJPXnOcabH-7Ag',
    appId: '1:719901521562:android:b420e1d18774ee0c295123',
    messagingSenderId: '719901521562',
    projectId: 'musicknew',
    storageBucket: 'musicknew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB24LFDurefhhPTmJZsOeqmdlLlzDD1c9o',
    appId: '1:719901521562:ios:3f0bbe00b1b93186295123',
    messagingSenderId: '719901521562',
    projectId: 'musicknew',
    storageBucket: 'musicknew.appspot.com',
    iosBundleId: 'com.example.musick',
  );
}
